name: nimbus
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_storage: ^12.4.5
  
  # Animation
  page_transition: ^2.2.1
  
  # Auth
  google_sign_in: ^6.3.0
  
  # Provider
  provider: ^6.1.4
  
  # Others
  pinput: ^5.0.1
  logger: ^2.5.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/.

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-UltraLight.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/Gilroy-UltraLightItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Gilroy-Thin.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/Gilroy-ThinItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Gilroy-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Gilroy-RegularItalic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Gilroy-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Gilroy-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Gilroy-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/Gilroy-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/Gilroy-BlackItalic.ttf
          weight: 900
          style: italic
